numbers = [1, 2, 3, 4, 5]
print(numbers[0:4])
print(numbers[0:5])
print(numbers[1:5])
print(numbers[:4])
print(numbers[0:])
print(numbers[-1:])
print(numbers[-4:])
print(numbers[-4:-3])
print(numbers[-4:-1])
print(numbers[:])
print(numbers[:-4])
print(numbers[:-5])
